PRODUCTS = [
    {
        "id": 1,
        "name": "Cheesecake de Frutos Rojos",
        "description": "Masa sablée, crema a base de tofu y queso crema cubierto de mermelada casera de frutos rojos.",
        "price": 11800,
        "gluten_free": False,
    },
    {
        "id": 2,
        "name": "Torta de Maracuyá",
        "description": "Base realizada en frutas secas, mousse de maracuyá. Decorada en la superficie con mermelada casera de maracuyá, copos de crema y praline de nueces.",
        "price": 11800,
        "gluten_free": True,
    },
    {
        "id": 3,
        "name": "Dulce Pistacho",
        "description": "Base realizada en frutos secos, primera capa de crema a base de yogurt de soja, queso crema de castañas y ralladura de limón, segunda capa con pasta de pistachos y fideos kataifi. Cubierta con ganache de chocolate amargo.",
        "price": 11800,
        "gluten_free": True,
    },
    {
        "id": 4,
        "name": "Lemon Pie",
        "description": "Masa sablée rellena de crema pastelera de limón decorada con copos de crema.",
        "price": 11800,
        "gluten_free": False,
    },
    {
        "id": 5,
        "name": "Orange Pie",
        "description": "Masa sablée rellena de crema pastelera de naranja decorada con copos de crema.",
        "price": 11800,
        "gluten_free": False,
    },
    {
        "id": 6,
        "name": "Torta Oreo",
        "description": "Bizcochos de chocolate rellenos de mousse de chocolate y crema con galletitas Oreo. La superficie está cubierta por una ganache de chocolate semi amargo.",
        "price": 11800,
        "gluten_free": False,
    },
    {
        "id": 7,
        "name": "Torta Matilda",
        "description": "Bizcochos de chocolate rellenos de mousse de chocolate. La superficie está cubierta por una ganache de chocolate semi amargo.",
        "price": 11800,
        "gluten_free": False,
    },
    {
        "id": 8,
        "name": "Torta Brownie",
        "description": "Brownie de chocolate semi amargo con copos de dulce de leche de almendras, corazón de frutos rojos. La superficie está decorada con crema.",
        "price": 11800,
        "gluten_free": False,
    },
    {
        "id": 9,
        "name": "Key Lime",
        "description": "Base realizada en frutos secos, crema de limas decorada con crema chantilly y limas en mitades.",
        "price": 11800,
        "gluten_free": False,
    },
]
